# Generated by Django 5.0.2 on 2024-03-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('vg', 'vegitable'), ('ft', 'fruits'), ('bd', 'bread'), ('mt', 'meat')], max_length=2)),
                ('product_image', models.ImageField(upload_to='static/product')),
            ],
        ),
    ]
