# Generated by Django 5.0.2 on 2024-04-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_user_propic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vg', 'vegitables'), ('ft', 'fruits'), ('bd', 'bread'), ('mt', 'meat')], max_length=2),
        ),
    ]
